import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   docsSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };


const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description: 'Start building your Flutter app with our guides.',
        slug: 'getting-started-with-flutter',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [
        'getting-started-with-flutter/setting-up-your-dev-environment',
        'getting-started-with-flutter/running-on-android',
        'getting-started-with-flutter/running-on-iOS',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      link: {
        type: 'generated-index',
        title: 'Development',
        description: 'Learn how to develop features in your Flutter app.',
        slug: 'development',
        keywords: ['development'],
        image: '/img/docusaurus.png',
      },
      items: [
        'development/file-structure',
        'development/dependencies',
        'development/code-snippets',
      ]
    },
    {
      type: 'category',
      label: 'Firebase Integration',
      link: {
        type: 'generated-index',
        title: 'Firebase Integration',
        description: 'Integrate Firebase with your Flutter app.',
        slug: 'firebase-integration',
        keywords: ['firebase', 'integration'],
        image: '/img/docusaurus.png',
      },
      items: [
        'firebase-integration/create-a-firebase-account',
        'firebase-integration/configure-a-firebase-project',
        'firebase-integration/enable-firebase-auth',
        'firebase-integration/enable-firebase-firestore',
        'firebase-integration/enable-firebase-storage',
        'firebase-integration/link-firebase-account-to-your-mobile-app',
        'firebase-integration/enable-SMS-phone-authentication',
      ],
    },
    {
      type: 'category',
      label: 'Core Modules',
      link: {
        type: 'generated-index',
        title: 'Core Modules',
        description: 'Integrate our core modules with your Flutter app.',
        slug: 'core-modules',
        keywords: ['core', 'modules'],
        image: '/img/docusaurus.png',
      },
      items: [
        'core-modules/ads',
        'core-modules/chat',
        'core-modules/authentication',
        'core-modules/user-reporting',
        'core-modules/video-chat',
        'core-modules/profile',
        'core-modules/in-app-purchases',
      ],
    },
    {
      type: 'category',
      label: 'Push Notifications',
      link: {
        type: 'generated-index',
        title: 'Push Notifications',
        description: 'Send push notifications to your Flutter app.',
        slug: 'push-notifications',
        keywords: ['push', 'notifications'],
        image: '/img/docusaurus.png',
      },
      items: [
        'push-notifications/push-notifications-setup',
        'push-notifications/push-notifications-on-android',
        'push-notifications/push-notifications-on-iOS',
      ]
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        title: 'Tutorials',
        description: 'Learn how to build features in your Flutter app.',
        slug: 'tutorials',
        keywords: ['tutorials'],
        image: '/img/docusaurus.png',
      },
      items: [
        'tutorials/add-maps-in-flutter-apps',
        'tutorials/how-to-deploy-your-firebase-functions',
        'tutorials/how-to-setup-firebase-localhost-for-testing',
        'tutorials/how-to-integrate-chatgpt-api-in-flutter',
        'tutorials/how-to-use-firebase-firestore-in-flutter',
        'tutorials/how-to-use-camera-in-flutter',
        'tutorials/flutter-local-biometrics-authentication',
        'tutorials/how-to-get-user-location-in-flutter',
        'tutorials/persistent-storage-in-flutter',
        'tutorials/flutter-webview',
        'tutorials/how-to-Implement-beautiful-charts-in-flutter',
        'tutorials/how-to-implement-gradients-in-flutter',
        'tutorials/how-to-generate-haptic-feedback-in-flutter',
        'tutorials/implementing-firebase-authentication-in-flutter',
        'tutorials/flutter-phone-auth-with-firebase',
        'tutorials/how-to-integrate-supabase-in-flutter',
        'tutorials/best-debugging-tools-for-flutter',
        'tutorials/how-to-implement-video-calls-in-flutter-with-twilio',
        'tutorials/how-to-build-an-audio-player-in-flutter'
      ]
    },
  ],
};

module.exports = sidebars;

export default sidebars;
